# Generated by Django 5.0.7 on 2024-08-16 00:04

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=765, unique=True)),
                ("username", models.CharField(blank=True, max_length=765)),
                ("password", models.CharField(max_length=120)),
                ("deleted", models.IntegerField(blank=True, null=True)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "custom_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
